"""Add conversation analytics tables

Revision ID: 47cdd40a14b1
Revises: a4178eb31991
Create Date: 2025-10-25 17:08:47.409873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cdd40a14b1'
down_revision = 'a4178eb31991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###