"""Add missing conversation fields

Revision ID: a4178eb31991
Revises: 001
Create Date: 2025-10-24 12:27:15.562567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4178eb31991'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_analytics', sa.Column('analytics_metadata', sa.JSON(), nullable=True))
    op.drop_column('conversation_analytics', 'metadata')
    op.add_column('conversations', sa.Column('conversation_metadata', sa.JSON(), nullable=True))
    op.drop_column('conversations', 'metadata')
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.drop_column('messages', 'metadata')
    op.add_column('system_metrics', sa.Column('system_metadata', sa.JSON(), nullable=True))
    op.drop_column('system_metrics', 'metadata')
    op.add_column('user_activities', sa.Column('activity_metadata', sa.JSON(), nullable=True))
    op.drop_column('user_activities', 'metadata')
    op.add_column('users', sa.Column('user_metadata', sa.JSON(), nullable=True))
    op.drop_column('users', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_metadata')
    op.add_column('user_activities', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_activities', 'activity_metadata')
    op.add_column('system_metrics', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('system_metrics', 'system_metadata')
    op.add_column('messages', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('messages', 'message_metadata')
    op.add_column('conversations', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'conversation_metadata')
    op.add_column('conversation_analytics', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('conversation_analytics', 'analytics_metadata')
    # ### end Alembic commands ###