"""remove_conversation_analytics_foreign_key

Revision ID: b947dd71c64d
Revises: 47cdd40a14b1
Create Date: 2025-10-26 12:13:00.153168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b947dd71c64d'
down_revision = '47cdd40a14b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_analytics_conversation_id_fkey'), 'conversation_analytics', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('conversation_analytics_conversation_id_fkey'), 'conversation_analytics', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###